production:
  env:
    app_path:
    server_name: Gimle
    gvtype: FE
    data_size: 6
  memcache:
    server: localhost:11211
    namespace: hoge
    expire: 30
development:
  env:
    app_path:
    server_name: Nounai
    gvtype: FE
    data_size: 6
  memcache:
    server: localhost:11211
    namespace: devel
    expire: 3
test:
  env:
    app_path:
    server_name: SakrayJ
    gvtype: FE
    data_size: 6
  memcache:
    server: localhost:11211
    namespace: test
    expire: 1
